In [1]:
import numpy as np
t1 = np.arange(1,6)
t2 = np.zeros((len(t1)-1)*3+len(t1), dtype = int)
t2[::4] = t1
t2
        

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [42]:
t3 = np.random.rand(3,3)
print(t3)
t4 = np.copy(t3[1])
t3[1] = t3[2]
t3[2] = t4
t3

[[0.53929901 0.22789544 0.08361642]
 [0.54613765 0.36449701 0.29968246]
 [0.91816341 0.92086027 0.51066032]]


array([[0.53929901, 0.22789544, 0.08361642],
       [0.91816341, 0.92086027, 0.51066032],
       [0.54613765, 0.36449701, 0.29968246]])

In [15]:
t4 = np.random.randint(1,20,(10,3))
t4set = set()
for i in range(len(t4)):
    for k in t4[i]:
        t4set.add(k)
t4set        
        
        
        


                       


{1, 3, 4, 5, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}

In [19]:
t5 = np.random.randint(0,10,10)
t6 = np.arange(len(t5))
t8 = np.array([])
for i in t6:
    t7 = np.array([])
    for j in range(t5[i]): 
        t7 = np.append(t7, i)
    t8 = np.append(t8, t7)    
t8
    

array([0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2.,
       2., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4.,
       4., 5., 5., 5., 5., 5., 5., 5., 5., 6., 6., 6., 6., 6., 6., 6., 6.,
       7., 7., 7., 7., 7., 7., 7., 8., 8., 8., 8., 9.])

In [16]:
t9 = np.average(np.random.randint(0,10,10))
t9

4.0

In [36]:
t10 = np.random.randint(0,10,10)

def shift(arr, n):
    a = arr[:n]
    b = np.array({})
    for i in range(len(arr) - n):
        c = np.roll(arr,shift = -1)
        b = np.vstack((a, c[:3]))
        arr = c
        a = b
    return b    
print(shift(t10,3))        

[[1 6 8]
 [6 8 4]
 [8 4 3]
 [4 3 1]
 [3 1 6]
 [1 6 8]
 [6 8 4]
 [8 4 0]]


In [46]:
t11 = np.random.randint(0,2,10)
np.logical_not(t11, out=t11)

[0 1 1 0 0 0 0 0 1 1]


array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0])

In [3]:
import math
t12 = np.random.randint(0,20,20).reshape(10,2)
t13 = np.random.randint(0,20,20).reshape(10,2)
point = np.random.randint(0,20,2)
def k(a, b):
    return (a[0] - b[0])/(a[1] - b[1])
def quot(x,a,b):
    return (x - a[0])/k(a,b) + b[0]
def gener(fir, sec, point):
    inter = 30
    for k in range(len(fir)):
        for i in np.arange(-30.0,30.0,0.01):
            y_1qu = quot(i,fir[k],sec[k])
            int_point = [i,y_1qu]
            tmp = math.sqrt(pow((int_point[0] - point[0]),2) + pow((int_point[1] - point[1]), 2))
            if (tmp < inter):
                inter = tmp
        yield inter
for i in gener(t12,t13,point):
    print(i)
                
    

9.910757342963816
8.622212535074738
8.622212535074738
8.589558545117432
8.589558545117432
2.8603174648979084
2.8603174648979084
2.8603174648979084
1.2787302375435114
0.26776108753972405


In [4]:
t14 = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(t14)

In [5]:
t15 = np.random.randint(0,10,50)
print(np.bincount(t15).argmax())

5


In [10]:
from numpy.lib import stride_tricks
t16 = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (t16.shape[0] - n)
j = 1 + (t16.shape[1] - n)
C = stride_tricks.as_strided(t16, shape=(i, j, n, n), strides=t16.strides + t16.strides)
print(C)

[[[[3 4 2]
   [1 2 3]
   [4 4 3]]

  [[4 2 1]
   [2 3 4]
   [4 3 4]]

  [[2 1 4]
   [3 4 2]
   [3 4 3]]

  [[1 4 2]
   [4 2 0]
   [4 3 0]]

  [[4 2 3]
   [2 0 0]
   [3 0 4]]

  [[2 3 3]
   [0 0 4]
   [0 4 3]]

  [[3 3 0]
   [0 4 2]
   [4 3 1]]

  [[3 0 0]
   [4 2 4]
   [3 1 4]]]


 [[[1 2 3]
   [4 4 3]
   [2 2 2]]

  [[2 3 4]
   [4 3 4]
   [2 2 1]]

  [[3 4 2]
   [3 4 3]
   [2 1 1]]

  [[4 2 0]
   [4 3 0]
   [1 1 3]]

  [[2 0 0]
   [3 0 4]
   [1 3 3]]

  [[0 0 4]
   [0 4 3]
   [3 3 0]]

  [[0 4 2]
   [4 3 1]
   [3 0 0]]

  [[4 2 4]
   [3 1 4]
   [0 0 1]]]


 [[[4 4 3]
   [2 2 2]
   [1 0 0]]

  [[4 3 4]
   [2 2 1]
   [0 0 0]]

  [[3 4 3]
   [2 1 1]
   [0 0 1]]

  [[4 3 0]
   [1 1 3]
   [0 1 4]]

  [[3 0 4]
   [1 3 3]
   [1 4 1]]

  [[0 4 3]
   [3 3 0]
   [4 1 2]]

  [[4 3 1]
   [3 0 0]
   [1 2 1]]

  [[3 1 4]
   [0 0 1]
   [2 1 0]]]


 [[[2 2 2]
   [1 0 0]
   [0 2 3]]

  [[2 2 1]
   [0 0 0]
   [2 3 2]]

  [[2 1 1]
   [0 0 1]
   [3 2 3]]

  [[1 1 3]
   [0 1 4]
   [2 3 1]]

  [[1 3 3]
   

In [28]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [29]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)

In [30]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9997 9999 9996 9998 9995]


In [17]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [18]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 2 3 4]


In [19]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[3 2 3]
 [1 2 0]
 [0 4 2]
 [1 1 1]
 [4 1 3]
 [4 1 1]
 [3 0 1]
 [0 0 1]
 [4 3 1]
 [4 3 2]]
[[3 2 3]
 [1 2 0]
 [0 4 2]
 [4 1 3]
 [4 1 1]
 [3 0 1]
 [0 0 1]
 [4 3 1]
 [4 3 2]]


In [20]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [26]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


In [27]:
a = np.random.uniform(0,1,10)
b = np.random.uniform(0,1,10)

np.einsum('i->', a)       # np.sum(A)
np.einsum('i,i->i', a, b) # A * B
np.einsum('i,i', a, b)    # np.inner(A, B)
np.einsum('i,j->ij', a, b)    # np.outer(A, B)

array([[0.42849133, 0.28377504, 0.30364353, 0.22281065, 0.41994631,
        0.14900183, 0.03604319, 0.6095006 , 0.46966261, 0.7405524 ],
       [0.44008155, 0.29145084, 0.31185675, 0.22883743, 0.4313054 ,
        0.15303216, 0.03701812, 0.62598692, 0.48236647, 0.76058353],
       [0.11217282, 0.07428819, 0.07948947, 0.0583286 , 0.10993585,
        0.03900652, 0.00943559, 0.15955842, 0.12295086, 0.19386588],
       [0.39458012, 0.26131681, 0.2796129 , 0.2051772 , 0.38671136,
        0.13720968, 0.0331907 , 0.56126415, 0.43249307, 0.68194438],
       [0.01425101, 0.00943795, 0.01009875, 0.00741037, 0.01396682,
        0.00495559, 0.00119875, 0.02027112, 0.01562031, 0.02462972],
       [0.45430789, 0.30087245, 0.32193802, 0.23623497, 0.44524803,
        0.15797917, 0.03821479, 0.64622295, 0.49795974, 0.7851706 ],
       [0.07108427, 0.04707666, 0.05037273, 0.03696301, 0.0696667 ,
        0.02471855, 0.00597936, 0.10111267, 0.07791435, 0.12285342],
       [0.20469957, 0.13556547, 0.1450570