In [136]:
import numpy as np

print(np.__version__)
np.show_config()

np.zeros(10)

np.ones(10)

print(np.full(10, 2.5))

#python -c "import numpy as np; np.info(np.add)"

s= np.zeros(10)
s[4] = 1
print(s)

t1= np.arange(10, 50)
print(t1)

print(np.flip(t1))



[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [147]:
t2 = np.arange(9).reshape(3,3)
t2

t3 = np.nonzero([1.2, 0.0, 4.0])
t3

t4 = np.random.rand(3,3,3)
t4

t5 = np.random.rand(10, 10)
np.min(t5)
np.max(t5)

t6 = np.random.random(30)
print(np.average(t6))

t7 = np.ones((5,5))
t7[1:len(t7)-1,1:len(t7)-1] = 0
t7

0*np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan

t8 = np.diag(np.arange(1,5), k = -1)
t8

t9 = np.ones((8,8))
t9[0::2, 0::2]=0
t9[1::2, 1::2]=0
t9

t10 = np.ones((6, 7, 8)).tolist()
count = 0
for i in range(len(t10)):
    for k in range(len(t10[i])):
        for l in range(len(t10[i][k])):
            if count == 100:
                print(i, k, l)
            count = count + 1  
            
t11 = np.tile([[1,0],[0,1]], (4,4))
t11

    


    

0.5424107683845322
1 5 4


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])